{% set version = "0.8.6" %}
package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/f5/18/6c4a5ed2e9d830bc30b5a40853bfd65e86f10276dd98a7921bb30411856d/Glymur-0.8.6.tar.gz
  sha256: 3008b482e7e427a8ebf79b96cbe82300d9b3f8c2275b944486991f74ffd6ec58

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - mock
    - contextlib2 >=0.4

  run:
    - python
    - numpy >=1.7.0
    - lxml >=2.3.2
    - contextlib2 >=0.4

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib
    - glymur.lib.test
    - glymur.test

  commands:
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  summary: 'Tools for accessing JPEG2000 files'

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
