{% set version = "0.8.7" %}
package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/1a/a6/4cf6ffa0b999b2b413c0d13182d59f3e5e21ee1e1b4217ef8c7c2eb8cb33/Glymur-0.8.7.tar.gz
  sha256: b24fcee2ba162467f47f2faeabfc261321debb372ed12c3d9d148f63ed487eb1

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - mock
    - contextlib2 >=0.4

  run:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - contextlib2 >=0.4
    - openjpeg 2.1.*

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib
    - glymur.lib.test
    - glymur.test

  commands:
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  summary: 'Tools for accessing JPEG2000 files'

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
