{% set version = "0.8.5" %}
package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/01/ca/59212eaafa272fe274c6409a141ac37fb2463b3cd12cb8cd6d81a30f3d76/Glymur-0.8.5.tar.gz
  md5: 99333e3a9dae7c3eb4511a2a4fa5eb0a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - mock
    - contextlib2 >=0.4

  run:
    - python
    - numpy >=1.7.0
    - lxml >=2.3.2
    - contextlib2 >=0.4

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib
    - glymur.lib.test
    - glymur.test

  commands:
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  summary: 'Tools for accessing JPEG2000 files'

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
