{% set version = "0.8.4" %}
package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/5c/8f/5633be85458c3b519262a36b10b3b9ea274acfc6d21945d005bef455093e/Glymur-0.8.4.tar.gz
  md5: 8185ffeb8d11d1f9c14f179b581e7d96

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - mock
    - contextlib2 >=0.4

  run:
    - python
    - numpy >=1.7.0
    - lxml >=2.3.2
    - contextlib2 >=0.4

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib
    - glymur.lib.test
    - glymur.test

  commands:
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  summary: 'Tools for accessing JPEG2000 files'

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
